title: Patterns, Code & Curiosity
email: orjan@hoyd.net
description: >- # this means to ignore newlines until "baseurl:"
    Writing about command line things, programming, photography, recreational math, art, curiosities and theology.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.hoyd.no" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  orjanv

plugins:
    - jekyll-feed

show_excerpts: true
date_format: "%d. %b, %Y"

# Build settings
theme: jekyll-theme-minima
minima:
    skin: dark

    nav_pages:
        - about.md
     
    social_links:
        - title: Mastodon
          icon: fa-mastodon
          url: "https://mastodon.scot/@hoyd"


