title: blog.hoyd.no
remote_theme: jekyll/minima

show_excerpts: true
date_format: "%d. %b, %Y"

nav_pages:
    - about.md

social_links:
    - title: Mastodon
      icon: fa-mastodon
      url: "https://mastodon.scot/@hoyd"
